config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :patients do
    resources :appointments
  end
  resources :schedulers

  # get 'appointments/home'
  #
  get '/appointments' => 'appointments#index', as: :appointments
  #
  # get '/appointments/new' => 'appointments#new', as: :schedule
  #
  # post 'appointments/create'

  # get 'schedulers/index'
  #
  # get 'schedulers/new'
  #
  # get 'schedulers/create'

  # get 'patients/index'
  #
  # get 'patients/new'
  #
  # get 'patients/create'
end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  belongs_to :patient
  belongs_to :scheduler

  def check_scheduler
    scheduler ? self.scheduler.name : ""
  end
end

app/models/patient.rb
class Patient < ActiveRecord::Base

  has_many :appointments
  has_many :schedulers, through: :appointments
  validates_presence_of :name, :sex, :email
  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  validates_uniqueness_of :name, :message => "This name has been used"

  def self.search(search)
    if search
      find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
    else
      find(:all)
    end
  end

  # t.string   "name"
  # t.string   "sex"
  # t.string   "email"
  # t.datetime "created_at", null: false
  # t.datetime "updated_at", null: false
end

app/models/scheduler.rb
class Scheduler < ActiveRecord::Base
  has_many :appointments
  has_many :patients, through: :appointments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :load_patient, except: [:index]
  before_action :build_appointment_params,  only: [ :new]
  before_action :build_appointment_from_params, only: [:create]
  before_action :load_appointment, only: [:show, :edit, :destroy, :update]

  def home
  end

  def index
    @appointments = Appointment.all
  end

  def new
    @appointment =  Appointment.new(patient: @patient)
  end

  def create
    if @appointment.save
      PatientMailer.notification_mail(@patient).deliver_now!
      redirect_to @patient
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @appointment.update(appointment_params)
      redirect_to @patient
    else
      render 'edit'
    end
  end

  def destroy
     if @appointment.destroy
       flash[:notice] = 'Appointment has been deleted!'
       redirect_to @patient
     end
  end

  def load_patient
    @patient = Patient.find(params[:patient_id])
  end

  def build_appointment_params
    @appointment =  Appointment.new(patient: @patient)
  end

  def build_appointment_from_params
    @appointment = @patient.appointments.build(appointment_params)
  end

  def load_appointment
    @appointment =  @patient.appointments.find(params[:id])
  end

  private
    def appointment_params
      params.require(:appointment).permit(:patient_id, :scheduler_id, :reason, :appointment_date, :appointment_time)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, :only  => [:show, :destroy]
  def index
    if params[:search]
      @patients = Patient.search(params[:search])
    else
      @patients = Patient.all
    end
  end

  def new
    @patient = Patient.new
  end

  def create
    @patient = Patient.new(patient_params)
    # require 'pry'; binding.pry
    if @patient.save
      redirect_to new_patient_appointment_path(@patient)
    else
      render 'new'
    end
  end

  def show

  end

  def destroy
    @patient.destroy
    redirect_to root_url, notice: "Patient has been deleted."
  end


  private
    def patient_params
      params.require(:patient).permit(:name, :sex, :email)
    end

  def set_patient
    @patient = Patient.find(params[:id])
  end
end

app/controllers/schedulers_controller.rb
class SchedulersController < ApplicationController
  def index
    @schedulers = Scheduler.all
  end

  def new
    @scheduler = Scheduler.new
  end

  def show
    @scheduler = Scheduler.find(params[:id])
  end

  def create
    @scheduler = Scheduler.create(scheduler_params)
    if @scheduler.save
      redirect_to schedulers_path
    else
      render 'new'
    end
  end

  private
    def scheduler_params
      params.require(:scheduler).permit(:name, :role)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  def user_facing_flashes
    flash.to_hash.slice("alert", "error", "notice", "success")
  end
end

app/views/application/_analytics.html.erb
<% if ENV["SEGMENT_KEY"] %>
  <script type="text/javascript">
    window.analytics=window.analytics||[],window.analytics.methods=["identify","group","track","page","pageview","alias","ready","on","once","off","trackLink","trackForm","trackClick","trackSubmit"],window.analytics.factory=function(t){return function(){var a=Array.prototype.slice.call(arguments);return a.unshift(t),window.analytics.push(a),window.analytics}};for(var i=0;i<window.analytics.methods.length;i++){var key=window.analytics.methods[i];window.analytics[key]=window.analytics.factory(key)}window.analytics.load=function(t){if(!document.getElementById("analytics-js")){var a=document.createElement("script");a.type="text/javascript",a.id="analytics-js",a.async=!0,a.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n)}},window.analytics.SNIPPET_VERSION="2.0.9",
    window.analytics.load("<%= ENV["SEGMENT_KEY"] %>");
    window.analytics.page();
  </script>
<% end %>

app/views/application/_flashes.html.erb
<% if flash.any? %>
  <div class="flashes">
    <% user_facing_flashes.each do |key, value| -%>
      <div class="flash-<%= key %>"><%= value %></div>
    <% end -%>
  </div>
<% end %>

app/views/application/_javascript.html.erb
<%= javascript_include_tag :application %>

<%= yield :javascript %>

<%= render "analytics" %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.fx.off = true;
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>

app/views/appointments/_form.html.erb
<div class="form container schedule-form">
  <h5>Schedule Appointment for <%= @patient.name %></h5>
  <%= simple_form_for [@patient, @appointment] do |f| %>
      <div class="input-field">
        <%= f.label :reason_for_appointment %>
        <%= f.text_field :reason %>
      </div>
      <div class="input-field">
        <!--<%= f.label :appointment_date %>-->
        <p>Appointment Date</p><%= f.date_field(:appointment_date) %>
      </div>
      <div class="input-field">
        <!--<%= f.label :appointment_time %>-->
        <p>Appointment Date</p><%= f.time_field(:appointment_time) %>
      </div>
      <%= f.association :scheduler, collection: Scheduler.all %>
      <div class="home-container waves-effect waves-light btn-large">
        <%= f.submit %>
      </div>
  <% end %>
</div>

app/views/appointments/edit.html.erb
<%= render 'form' %>

app/views/appointments/index.html.erb
<div class="container">
  <h3>Appointments List</h3>
  <div class="appointment">
    <% @appointments.each do |appointment| %>
        <div class="card card-container">
          <div class="card-content">
            <p> Patient name: <%= appointment.patient.name %> </p>
            <p> Reason for Appointment: <%= appointment.reason %> </p>
            <p> Staff to See: <%= appointment.check_scheduler %> </p>
            <p> Appointment Details: <%= appointment.appointment_date %> <%= appointment.appointment_time.try(:strftime, "%I.%M %P") %> </p>
          </div>
        </div>
    <% end %>
    <div class="home-container waves-effect waves-light btn-large">
      <%= link_to 'Back to home page', root_url %>
    </div>
  </div>
</div>

app/views/appointments/new.html.erb
<%= render 'form' %>

app/views/home/index.html.erb
<div class="head-section">
  <div class="home-page-text">
    <h3>Welcome to Appointments!</h3>
    <div class="home-page-container">
      <ul>
        <li>
          <%= link_to 'schedule appointments', patients_path, class:'home-container waves-effect waves-light btn-large' %>
        </li>
        <br>
        <li>
          <%= link_to 'view appointments', appointments_path(@appointments), class:'home-container waves-effect waves-light btn-large' %>
        </li>
        <br>
        <li>
          <%= link_to "Add new staff", new_scheduler_path, class:'home-container waves-effect waves-light btn-large' %>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Appointments!</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
  <nav>
    <div class="nav-wrapper">
      <%= link_to 'Appointments', root_url, class: "nav-text" %>
    </div>
  </nav>
</header>
<%= yield %>
</body>
</html>

app/views/patients/_form.html.erb
<div class="container form">
  <h3>Add Patient</h3>
  <%= form_for @patient do |f| %>

        <% if @patient.errors.any? %>
          <div class="error-validation">
            <ul>
              <% @patient.errors.full_messages.each do |error| %>
                  <li><%= error %></li>
              <% end %>
            </ul>
          </div>
        <%  end %>
        <div class="input-field">
          <%= f.label :name %>
          <%= f.text_field :name %>
        </div>
        <div class="input-field">
          <%= f.label :sex %>
          <%= f.text_field :sex %>
        </div>
        <div class="input-field">
          <%= f.label :email %>
          <%= f.text_field :email %>
        </div>
        <div class="home-container waves-effect waves-light btn-large">
          <%= f.submit %>
        </div>


  <% end %>
</div>

app/views/patients/index.html.erb
<div class="container">
  <h3>Patients List</h3>
    <% @patients.each do |patient| %>
    <div class="card card-container">
      <div class="card-content">
        <b>Patient name: <%= patient.name %></b>
        <p>Sex: <%= patient.sex %></p>
        <p>Email: <%= patient.email %></p>
      </div>
      <div class="card-action">
        <p>
          <%= link_to 'create appointment', new_patient_appointment_path(patient.id) %>
          <vr></vr>
          <%= link_to 'view appointments',  patient_path(patient.id) %>
        </p>
      </div>
    </div>
    <% end %>
    <div class="link-container waves-effect waves-light btn-large">
      <%= link_to 'Add new patient', new_patient_path %>
    </div>
    <vr></vr>
    <div class="home-container waves-effect waves-light btn-large">
      <%= link_to 'Back to home page', root_path %>
    </div>
</div>

app/views/patients/new.html.erb
<%= render 'form' %>

app/views/patients/show.html.erb
<div class="container">
  <h5> List of Appointments for <%= @patient.name %></h5>
  <% @patient.appointments.each do |p| %>
      <div class="card card-container">
        <div class="card-content">
          <p>Name: <%= p.patient.name %></p>
          <p>Doctor's Name: <%= p.check_scheduler %></p>
          <p>Reason: <%= p.reason %></p>
          <p>Appointment Details: <%= p.appointment_date %> <%= p.appointment_time.try(:strftime, "%I.%M %P") %></p>
        </div>
        <div class="card-action">
          <%= link_to "Delete Appointment", patient_appointment_path(p.patient, p), method: :delete, data: { confirm: "Are you sure?"} %>
          <%= link_to "Edit Appointment", edit_patient_appointment_path(p.patient, p) %>
        </div>
      </div>
  <% end %>
  <div class="link-container waves-effect waves-light btn-large">
    <%= link_to 'New Appointment', new_patient_appointment_path(patient_id:  @patient.id) %>
  </div>
  <vr></vr>
  <div class="home-container waves-effect waves-light btn-large">
    <%= link_to 'Back', patients_path %>
  </div>
</div>

app/views/schedulers/_form.html.erb
<div class="form container">
  <h3>New Staff Form</h3>
  <%= form_for @scheduler do |f| %>
      <div class="input-field">
        <%= f.label :staff_name %>
        <%= f.text_field :name %>
      </div>
      <div class="input-field">
        <%= f.label :designation_title %>
        <%= f.text_field :role %>
      </div>
      <div class="home-container waves-effect waves-light btn-large">
        <%= f.submit %>
      </div>

  <% end %>
</div>

app/views/schedulers/index.html.erb
<div class="container">
  <h3>Staff List</h3>
  <% @schedulers.each do |s| %>
    <div class="card card-container">
      <p> Staff Name: <%= s.name %> </p>
      <p> Title: <%= s.role %> </p>
    </div>
  <% end %>
  <div class="home-container waves-effect waves-light btn-large">
    <%= link_to 'Back to Home', root_url %>
  </div>
</div>

app/views/schedulers/new.html.erb
<%= render 'form' %>

app/views/schedulers/show.html.erb
<%= @scheduler.name %>